server:
  port: 9999
spring:
  datasource:
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/drools?useUnicode=true&allowMultiQueries=true&rewriteBatchedStatements=true&serverTimezone=GMT%2B8
  jpa:
      show-sql: true
  #Thymeleaf是一个XML/XHTML/HTML5模板引擎
  thymeleaf:
    prefix: classpath:/templates/

#mybatis配置
#Mapper.xml所在的位置
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  #entity扫描的包名
  type-aliases-package: com.droolsBoot.model
